#just in case, it shoud be true by default
/process/em/fluo true
/process/em/auger true
/process/em/augerCascade true 
/process/em/pixe true

#/run/numberOfThreads 4
#/PoSOS/det/setOutputDirectory /nfs/tegile/work/experiences/detecteurs/manzanillas/LEAPS_INNOV/Geant4_output/ 
/PoSOS/det/setSetupName run_1
#select output format, options are: csv root hdf5
/PoSOS/det/setDataType csv
#Set the position of the collimator, a values between -37 and 37 mm (size of samples)
#Choise of source type: 0 gamma,1 Fe-55,2 Cs-137; 1 Bi-207; 2 Sr-90; 3 e-

/run/initialize
/PoSOS/gun/sourceType 0
/PoSOS/gun/sourcePositionX 0.5 mm
/PoSOS/gun/sourcePositionY 1.0 mm
/PoSOS/gun/sourceDiameter 0.1 mm
/PoSOS/gun/sourceEnergy 7.0  keV
/PoSOS/gun/sourceGammaPolarizationAngle 90
/PoSOS/gun/sourceGammaPolarizationDegree 0.9

/run/beamOn 9000000
